// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: messages-ign.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//Ignition
type StateType int32

const (
	StateType_NA   StateType = 0
	StateType_UP   StateType = 1
	StateType_DOWN StateType = 2
)

// Enum value maps for StateType.
var (
	StateType_name = map[int32]string{
		0: "NA",
		1: "UP",
		2: "DOWN",
	}
	StateType_value = map[string]int32{
		"NA":   0,
		"UP":   1,
		"DOWN": 2,
	}
)

func (x StateType) Enum() *StateType {
	p := new(StateType)
	*p = x
	return p
}

func (x StateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_ign_proto_enumTypes[0].Descriptor()
}

func (StateType) Type() protoreflect.EnumType {
	return &file_messages_ign_proto_enumTypes[0]
}

func (x StateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateType.Descriptor instead.
func (StateType) EnumDescriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{0}
}

type StatusResponse_State int32

const (
	StatusResponse_STARTED StatusResponse_State = 0
	StatusResponse_STOPPED StatusResponse_State = 1
	StatusResponse_UNKNOWN StatusResponse_State = 2
)

// Enum value maps for StatusResponse_State.
var (
	StatusResponse_State_name = map[int32]string{
		0: "STARTED",
		1: "STOPPED",
		2: "UNKNOWN",
	}
	StatusResponse_State_value = map[string]int32{
		"STARTED": 0,
		"STOPPED": 1,
		"UNKNOWN": 2,
	}
)

func (x StatusResponse_State) Enum() *StatusResponse_State {
	p := new(StatusResponse_State)
	*p = x
	return p
}

func (x StatusResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_ign_proto_enumTypes[1].Descriptor()
}

func (StatusResponse_State) Type() protoreflect.EnumType {
	return &file_messages_ign_proto_enumTypes[1]
}

func (x StatusResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusResponse_State.Descriptor instead.
func (StatusResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{4, 0}
}

type Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Start) Reset() {
	*x = Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{0}
}

type Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Stop) Reset() {
	*x = Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{1}
}

type Restart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Restart) Reset() {
	*x = Restart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Restart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restart) ProtoMessage() {}

func (x *Restart) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restart.ProtoReflect.Descriptor instead.
func (*Restart) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{2}
}

type StatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{3}
}

func (x *StatusRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status StatusResponse_State `protobuf:"varint,1,opt,name=Status,proto3,enum=messages.StatusResponse_State" json:"Status,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetStatus() StatusResponse_State {
	if x != nil {
		return x.Status
	}
	return StatusResponse_STARTED
}

type InfoCounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
}

func (x *InfoCounterRequest) Reset() {
	*x = InfoCounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoCounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoCounterRequest) ProtoMessage() {}

func (x *InfoCounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoCounterRequest.ProtoReflect.Descriptor instead.
func (*InfoCounterRequest) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{5}
}

func (x *InfoCounterRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type InfoCounterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inputs  int64 `protobuf:"varint,1,opt,name=Inputs,proto3" json:"Inputs,omitempty"`
	Outputs int64 `protobuf:"varint,2,opt,name=Outputs,proto3" json:"Outputs,omitempty"`
}

func (x *InfoCounterResponse) Reset() {
	*x = InfoCounterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoCounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoCounterResponse) ProtoMessage() {}

func (x *InfoCounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoCounterResponse.ProtoReflect.Descriptor instead.
func (*InfoCounterResponse) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{6}
}

func (x *InfoCounterResponse) GetInputs() int64 {
	if x != nil {
		return x.Inputs
	}
	return 0
}

func (x *InfoCounterResponse) GetOutputs() int64 {
	if x != nil {
		return x.Outputs
	}
	return 0
}

type AddressCounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
}

func (x *AddressCounterRequest) Reset() {
	*x = AddressCounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressCounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressCounterRequest) ProtoMessage() {}

func (x *AddressCounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressCounterRequest.ProtoReflect.Descriptor instead.
func (*AddressCounterRequest) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{7}
}

func (x *AddressCounterRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type AddressCounterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *AddressCounterResponse) Reset() {
	*x = AddressCounterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressCounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressCounterResponse) ProtoMessage() {}

func (x *AddressCounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressCounterResponse.ProtoReflect.Descriptor instead.
func (*AddressCounterResponse) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{8}
}

func (x *AddressCounterResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AddressCounterResponse) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ValueEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State StateType `protobuf:"varint,1,opt,name=state,proto3,enum=messages.StateType" json:"state,omitempty"`
	Coord string    `protobuf:"bytes,2,opt,name=coord,proto3" json:"coord,omitempty"`
}

func (x *ValueEvent) Reset() {
	*x = ValueEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueEvent) ProtoMessage() {}

func (x *ValueEvent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueEvent.ProtoReflect.Descriptor instead.
func (*ValueEvent) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{9}
}

func (x *ValueEvent) GetState() StateType {
	if x != nil {
		return x.State
	}
	return StateType_NA
}

func (x *ValueEvent) GetCoord() string {
	if x != nil {
		return x.Coord
	}
	return ""
}

type IgnitionEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value     *ValueEvent `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp float64     `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type      string      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *IgnitionEvent) Reset() {
	*x = IgnitionEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IgnitionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnitionEvent) ProtoMessage() {}

func (x *IgnitionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnitionEvent.ProtoReflect.Descriptor instead.
func (*IgnitionEvent) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{10}
}

func (x *IgnitionEvent) GetValue() *ValueEvent {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *IgnitionEvent) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IgnitionEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type PowerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value     StateType `protobuf:"varint,1,opt,name=value,proto3,enum=messages.StateType" json:"value,omitempty"`
	Timestamp int64     `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PowerEvent) Reset() {
	*x = PowerEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PowerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerEvent) ProtoMessage() {}

func (x *PowerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerEvent.ProtoReflect.Descriptor instead.
func (*PowerEvent) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{11}
}

func (x *PowerEvent) GetValue() StateType {
	if x != nil {
		return x.Value
	}
	return StateType_NA
}

func (x *PowerEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SuspendPlatformEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value     *ValueEvent `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp float64     `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type      string      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *SuspendPlatformEvent) Reset() {
	*x = SuspendPlatformEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuspendPlatformEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendPlatformEvent) ProtoMessage() {}

func (x *SuspendPlatformEvent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendPlatformEvent.ProtoReflect.Descriptor instead.
func (*SuspendPlatformEvent) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{12}
}

func (x *SuspendPlatformEvent) GetValue() *ValueEvent {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SuspendPlatformEvent) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SuspendPlatformEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type IgnitionStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *IgnitionStateRequest) Reset() {
	*x = IgnitionStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IgnitionStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnitionStateRequest) ProtoMessage() {}

func (x *IgnitionStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnitionStateRequest.ProtoReflect.Descriptor instead.
func (*IgnitionStateRequest) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{13}
}

func (x *IgnitionStateRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type IgnitionStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State     StateType `protobuf:"varint,1,opt,name=State,proto3,enum=messages.StateType" json:"State,omitempty"`
	TimeStamp float64   `protobuf:"fixed64,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *IgnitionStateResponse) Reset() {
	*x = IgnitionStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IgnitionStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnitionStateResponse) ProtoMessage() {}

func (x *IgnitionStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnitionStateResponse.ProtoReflect.Descriptor instead.
func (*IgnitionStateResponse) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{14}
}

func (x *IgnitionStateResponse) GetState() StateType {
	if x != nil {
		return x.State
	}
	return StateType_NA
}

func (x *IgnitionStateResponse) GetTimeStamp() float64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type PowerStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *PowerStateRequest) Reset() {
	*x = PowerStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PowerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerStateRequest) ProtoMessage() {}

func (x *PowerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerStateRequest.ProtoReflect.Descriptor instead.
func (*PowerStateRequest) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{15}
}

func (x *PowerStateRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type IgnitionEventsSubscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *IgnitionEventsSubscription) Reset() {
	*x = IgnitionEventsSubscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IgnitionEventsSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnitionEventsSubscription) ProtoMessage() {}

func (x *IgnitionEventsSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnitionEventsSubscription.ProtoReflect.Descriptor instead.
func (*IgnitionEventsSubscription) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{16}
}

func (x *IgnitionEventsSubscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IgnitionEventsSubscription) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type IgnitionPowerSubscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *IgnitionPowerSubscription) Reset() {
	*x = IgnitionPowerSubscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IgnitionPowerSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnitionPowerSubscription) ProtoMessage() {}

func (x *IgnitionPowerSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnitionPowerSubscription.ProtoReflect.Descriptor instead.
func (*IgnitionPowerSubscription) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{17}
}

func (x *IgnitionPowerSubscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IgnitionPowerSubscription) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type DiscoverIgnition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *DiscoverIgnition) Reset() {
	*x = DiscoverIgnition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverIgnition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverIgnition) ProtoMessage() {}

func (x *DiscoverIgnition) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverIgnition.ProtoReflect.Descriptor instead.
func (*DiscoverIgnition) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{18}
}

func (x *DiscoverIgnition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiscoverIgnition) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type DiscoverResponseIgnition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr    string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout int64  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *DiscoverResponseIgnition) Reset() {
	*x = DiscoverResponseIgnition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_ign_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverResponseIgnition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponseIgnition) ProtoMessage() {}

func (x *DiscoverResponseIgnition) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ign_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponseIgnition.ProtoReflect.Descriptor instead.
func (*DiscoverResponseIgnition) Descriptor() ([]byte, []int) {
	return file_messages_ign_proto_rawDescGZIP(), []int{19}
}

func (x *DiscoverResponseIgnition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiscoverResponseIgnition) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *DiscoverResponseIgnition) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

var File_messages_ign_proto protoreflect.FileDescriptor

var file_messages_ign_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2d, 0x69, 0x67, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x07,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x22, 0x06, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x22,
	0x09, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x22, 0x27, 0x0a, 0x0d, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x22, 0x78, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2e, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x22, 0x2c, 0x0a,
	0x12, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x47, 0x0a, 0x13, 0x49,
	0x6e, 0x66, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x73, 0x22, 0x2f, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x3c, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41,
	0x64, 0x64, 0x72, 0x22, 0x4d, 0x0a, 0x0a, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x22, 0x6d, 0x0a, 0x0d, 0x49, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x55, 0x0a, 0x0a, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x74, 0x0a, 0x14, 0x53, 0x75, 0x73, 0x70,
	0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2e,
	0x0a, 0x14, 0x49, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x60,
	0x0a, 0x15, 0x49, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x2b, 0x0a, 0x11, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x40, 0x0a,
	0x1a, 0x49, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22,
	0x3f, 0x0a, 0x19, 0x49, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x77, 0x65, 0x72,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x22, 0x36, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x49, 0x67, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x58, 0x0a, 0x18, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x67, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x2a, 0x25, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x06, 0x0a, 0x02, 0x4e, 0x41, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x50, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x75, 0x6d, 0x61, 0x63, 0x70, 0x2f, 0x67,
	0x6f, 0x2d, 0x69, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_ign_proto_rawDescOnce sync.Once
	file_messages_ign_proto_rawDescData = file_messages_ign_proto_rawDesc
)

func file_messages_ign_proto_rawDescGZIP() []byte {
	file_messages_ign_proto_rawDescOnce.Do(func() {
		file_messages_ign_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_ign_proto_rawDescData)
	})
	return file_messages_ign_proto_rawDescData
}

var file_messages_ign_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_messages_ign_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_messages_ign_proto_goTypes = []interface{}{
	(StateType)(0),                     // 0: messages.StateType
	(StatusResponse_State)(0),          // 1: messages.StatusResponse.State
	(*Start)(nil),                      // 2: messages.Start
	(*Stop)(nil),                       // 3: messages.Stop
	(*Restart)(nil),                    // 4: messages.Restart
	(*StatusRequest)(nil),              // 5: messages.StatusRequest
	(*StatusResponse)(nil),             // 6: messages.StatusResponse
	(*InfoCounterRequest)(nil),         // 7: messages.InfoCounterRequest
	(*InfoCounterResponse)(nil),        // 8: messages.InfoCounterResponse
	(*AddressCounterRequest)(nil),      // 9: messages.AddressCounterRequest
	(*AddressCounterResponse)(nil),     // 10: messages.AddressCounterResponse
	(*ValueEvent)(nil),                 // 11: messages.ValueEvent
	(*IgnitionEvent)(nil),              // 12: messages.IgnitionEvent
	(*PowerEvent)(nil),                 // 13: messages.PowerEvent
	(*SuspendPlatformEvent)(nil),       // 14: messages.SuspendPlatformEvent
	(*IgnitionStateRequest)(nil),       // 15: messages.IgnitionStateRequest
	(*IgnitionStateResponse)(nil),      // 16: messages.IgnitionStateResponse
	(*PowerStateRequest)(nil),          // 17: messages.powerStateRequest
	(*IgnitionEventsSubscription)(nil), // 18: messages.IgnitionEventsSubscription
	(*IgnitionPowerSubscription)(nil),  // 19: messages.IgnitionPowerSubscription
	(*DiscoverIgnition)(nil),           // 20: messages.DiscoverIgnition
	(*DiscoverResponseIgnition)(nil),   // 21: messages.DiscoverResponseIgnition
}
var file_messages_ign_proto_depIdxs = []int32{
	1,  // 0: messages.StatusResponse.Status:type_name -> messages.StatusResponse.State
	0,  // 1: messages.ValueEvent.state:type_name -> messages.StateType
	11, // 2: messages.IgnitionEvent.value:type_name -> messages.ValueEvent
	0,  // 3: messages.PowerEvent.value:type_name -> messages.StateType
	11, // 4: messages.SuspendPlatformEvent.value:type_name -> messages.ValueEvent
	0,  // 5: messages.IgnitionStateResponse.State:type_name -> messages.StateType
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_messages_ign_proto_init() }
func file_messages_ign_proto_init() {
	if File_messages_ign_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_ign_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Restart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoCounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoCounterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressCounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressCounterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IgnitionEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PowerEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuspendPlatformEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IgnitionStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IgnitionStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PowerStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IgnitionEventsSubscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IgnitionPowerSubscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverIgnition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_ign_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverResponseIgnition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_ign_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_ign_proto_goTypes,
		DependencyIndexes: file_messages_ign_proto_depIdxs,
		EnumInfos:         file_messages_ign_proto_enumTypes,
		MessageInfos:      file_messages_ign_proto_msgTypes,
	}.Build()
	File_messages_ign_proto = out.File
	file_messages_ign_proto_rawDesc = nil
	file_messages_ign_proto_goTypes = nil
	file_messages_ign_proto_depIdxs = nil
}
